# Generated by Django 5.1.7 on 2026-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_certificado', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(upload_to='certificados/')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('link_github', models.URLField()),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(upload_to='projetos/')),
            ],
        ),
    ]
