# Generated by Django 5.1.7 on 2026-02-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/capas/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_breve',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_completa',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='projetos/detalhes/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.projeto')),
            ],
        ),
    ]
