# Generated by Django 5.1.7 on 2026-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projeto_descricao_remove_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_hab', models.CharField(max_length=80)),
                ('descricao_breve', models.CharField(max_length=300)),
                ('icone', models.CharField(help_text="Insira a classe do ícone (ex: 'lni lni-python')", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='descricao',
        ),
        migrations.AddField(
            model_name='certificado',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/capas/'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='descricao_breve',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
