# Generated by Django 5.1.7 on 2026-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_habilidade_remove_certificado_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='descricao_breve',
            field=models.TextField(max_length=300),
        ),
    ]
